### ISSUE TITLE
漫画検索の失敗

### ISSUE THREAD

**Issue by quiye** [hidesys/mantropy#29]
以下の4つの検索全て動かず......
- Amazonからいっぱい検索
- 密林もちょっと
- 漫トロピーWebだけ
- 自分のを探す

**Comment by quiye** [comment]
- 漫トロピーWebだけ
- 自分のを探す

が治りました👍

残り
- Amazonからいっぱい検索
- 密林もちょっと

です

**Comment by NakashoyaHidetaro** [comment]
wei
