### ISSUE TITLE
漫画タイトルの編集に失敗する

### ISSUE THREAD

**Issue by quiye** [hidesys/mantropy#30]
firefox on ubuntuで確認
![image](https://user-images.githubusercontent.com/13133179/30519609-a8c2e234-9bd5-11e7-83eb-4b7a07122b9a.png)
掲載雑誌を追加したり"細部"にコメントをした後なら漫画タイトルの編集に成功する

**Comment by NakashoyaHidetaro** [comment]
対応済み
