### ISSUE TITLE
ランキングから漫画を削除できない

### ISSUE THREAD

**Issue by quiye** [hidesys/mantropy#33]
右側の**削除**を押すと
![image](https://user-images.githubusercontent.com/13133179/30519786-6ea783c6-9bd9-11e7-80ef-4439079b3b6f.png)

RanksController#show is missing a template for this request format and variant. request.formats: ["text/html"] request.variant: [] NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.

**Comment by NakashoyaHidetaro** [comment]
Deleteメソッドが上手く動いていない

**Comment by quiye** [comment]
jsの読み込み順によってreference依存関係が正しく機能しないことが原因らしい

**Comment by NakashoyaHidetaro** [comment]
JSをprecompile通るようにしたので直った
